### ISSUE TITLE
Can you provide the training codes and settings?

### ISSUE THREAD

**Issue by NanAlbert** [shiming-chen/TransZero#1]
Hello. I am very interested in this work. But it only contains the test codes, can you provide the training codes and the corresponding settings?

**Comment by NanAlbert** [comment]
Also, I cannot download the model on Google Drive. I only have the view permission.

**Comment by shiming-chen** [comment]
Hi, @NanAlbert .
Thank you for interesting in our work.  We have released all the codes and settings.

Best!

Shiming

**Comment by imogenqi** [comment]
@shiming-chen Thanks for your work!   I have the same question, can you provide the training codes and the corresponding settings? Thank you!

**Comment by shiming-chen** [comment]
> @shiming-chen Thanks for your work! I have the same question, can you provide the training codes and the corresponding settings? Thank you!

We will release the training codes as soon as possible. Thank you for interesting in our works.

**Comment by shiming-chen** [comment]
Hi, @imogenqi 

Thank you for interesting in our work. We have released all the codes and settings.

Best!

Shiming
